
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
  {{- include "openssh-server.labels" . | nindent 4 }}
  annotations:
  {{-  .Values.service.annotations | toYaml | nindent 4 }}
