apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openssh-server.fullname" . }}-initscript
  labels:
  {{- include "openssh-server.labels" . | nindent 4 }}
data:
  init.sh: {{ .Values.initScript | toYaml | indent 2 }}
