{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "openssh-server.fullname" . }}
  labels:
    {{- include "openssh-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "openssh-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.networkPolicy.ingress }}
    {{- range .Values.networkPolicy.ingress }}
    - {{ . | toYaml | nindent 6 }}
    {{- end }}
    {{- end }}
{{- end -}}
