apiVersion: v1
kind: Service
metadata:
  name: sshd-anyuid-service
  namespace: sshd
spec:
  selector:
    pod: sshd-anyuid-label
  ports:
    - name: ssh-tcp
      protocol: TCP
      port: 2022
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd-anyuid-deployment
  namespace: sshd
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      pod: sshd-anyuid-label
  template:
    metadata:
      labels:
        pod: sshd-anyuid-label
    spec:
      # A Service Account can be used for setting the SCC if /sbin/nologin changes are not desired
      serviceAccount: sshd-sa
      imagePullSecrets:
        - name: regcred
      containers:
        - name: sshd-anyuid
          securityContext:
            runAsUser: 1000
          image: quay.io/mwasher/sshd:latest
          ports:
            - name: ssh
              containerPort: 2022
          env:
            - name: TZ
              value: Australia/Brisbane
          volumeMounts:
          - name: sshd-keys
            mountPath: /opt/ssh/sshd_config
            subPath: sshd_config
          - name: authorized-keys
            mountPath: /opt/ssh/authorized_keys
            subPath: authorized_keys
          - name: emptydir
            mountPath: /tmp/ssh
          - name: init-script
            mountPath: /init.sh
            subPath: init.sh
            
      volumes:
      - name: sshd-keys
        secret:
          secretName: sshd-keys
      - name: authorized-keys
        configMap:
          name: authorized-keys
      - name: emptydir
        emptyDir: {}
      - name: init-script
        configMap:
          name: init-script
          defaultMode: 111
